### PR TITLE
Deterministic Builds 

### PR DESCRIPTION
**Pull request by kentsommer**
Remaining work / notes:

1. This PR includes my public key which I was using for testing. This key should be replaced (and removed from the repo) with core developer GPG keys. 
    * Keys should be [placed here](https://github.com/MyHush/hush/tree/master/contrib/gitian-downloader)
    * References to these keys should be [updated here](https://github.com/MyHush/hush-gitian/blob/master/roles/gitian/defaults/main.yml)

2. There are a few `TODO:` sections left in [MyHush/hush-gitian](https://github.com/MyHush/hush-gitian). 
    * [Update main.yml](https://github.com/MyHush/hush-gitian/blob/master/roles/gitian/defaults/main.yml)
    * [Update keys.yml](https://github.com/MyHush/hush-gitian/blob/master/roles/gitian/tasks/keys.yml)

3. Finally, [the `hush_version` tag](https://github.com/MyHush/hush-gitian/blob/master/gitian.yml) (currently pointing to `1.0.12-dev`) should point to `1.0.12`. However, before that happens, the `1.0.12` release needs to be updated to include these PR'ed changes. 

If I am given a list of GPG keys I am happy to PR the required changes listed in item 1. I can also PR the changes in 2 if you would like but it is probably just faster for one of you to update them quick. 

t1JjmKWun4jn61JgVSK1fQKifVToqhKsov3

### CODE REVIEW

**Comment by madbuda** [comment]
please test this

**Comment by madbuda** [comment]
test this please

**Comment by kentsommer** [comment]
:LGTM: 

@radix42 Can I merge this in? I will update the required references mentioned in the PR after this is merged.

**Comment by kentsommer** [comment]
This is merged by https://github.com/MyHush/hush/pull/68

I'll make the necessary changes listed in this PR and then close this out.

**Comment by kentsommer** [comment]
Apart from the version tag that is necessary, this is all updated and fixed. Once the commits are on master everything will work :+1: 

I'm closing this out.

**Pull request closed without merging**
