### PR TITLE
Create Testnet.md (Issue #10)

### PR DESCRIPTION
**Pull request by Scottrock**
Instructions for running a Testnet - answers Issue #10

### CODE REVIEW

**Comment by madbuda** [comment]
If you are going to be running testnet and mainnet you should be using 2 config directories since you are running 2 instances of hushd    
Might want to mention turning on cpu mining on the testnet node

**Comment by Scottrock** [comment]
I agree on the CPU mining addition, and how to limit to one thread to keep the difficulty low. I can add this as a config / command line pair for simplicity (to keep one config file).
Or I can add as two config files (and hence two chain directories) if we switch from `hushd -testnet` to `hushd -datadir=~/.hush-t` and then put `/.hush-t/hush.conf` 

However, running two instances of hushd on one config directory is completely acceptable for a 'default' setup where no mining etc change is needed.

If we want to get really fancy - I use two bash scripts in /usr/bin/ to create `husht` and  `husht-cli` which contain the `hushd -datadir=xxx` and `hush-cli -rpcport=xxx` details

**Comment by leto** [comment]
I haven't fully tested every command, but this looks awesome and I am :+1: to merging this

**Comment by leto** [comment]
This was blessed by @radix42 , thanks for your PR @Scottrock !

**Pull request merged**
