### PR TITLE
Help2Man docs, Hush-Tx fixes, and bit of branding

### PR DESCRIPTION
**Pull request by csharpee**
- hush-tx builds and is functional.
- help2man pages have been fixed / updated. The generation of the hush-tx gave a STDOUT error, so i used -f to create the file with the errors, then fixed them.
- Not much branding updates.

I tested the version for all the help2man pages. The only problem with using -f is it forced it which resulted in .dirty and errors, but still populated the hush-tx manual. The help file works, but the -version does not. 

After the tests, I built via build.sh and ./src/hushd -testnet
The node is mining and running now.

### CODE REVIEW

**Comment by radix42** [comment]
did this stuff get merged outside of this pull request into 1.0.12?

**Comment by csharpee** [comment]
No.
This was initially before the 1.0.12 release, then I recreated the PR again after some failed attempts -- I can redo the changes. After the hush team merge from 1.0.9 to master, my repo of hush was entirely different and a merge was going to be more work than redoing the above changes.

**Comment by radix42** [comment]
yeah that's a rebase situation, and rebase is not my personal strong suit
with git :-)
but rebasing this PR on top of master would be what I think we "should"
do....or its spiritual equivalent by other means

**Comment by csharpee** [comment]
Okay, 

The updated PR is linked here @radix42: 

https://github.com/csharpee/hush/tree/hush-tx
https://github.com/csharpee/hush/tree/hush-help

I am still learning myself with Git. I enjoy the complexities of git, I wish it was more intuitive though.

The following holds true for the initial update + I added hush-tx support for zcutil/build-debian-package.sh. Each branch was tested and compiled before pushing and this comment.

**Pull request closed without merging**
